#Service Module

from DomainBook import Book
import random
import copy

class Service:

    def __init__(self):
        self.currentBook = Book
        self.mainShelf = []
        self.historyShelf = []
    
    def addRandomBook(self):
        listOfAdjectives = [
            "surrendering",  
            "impenetrable",  
            "sentimental",  
            "unbreakable",  
            "cooperative",  
            "magnificent",  
            "penetrating",  
            "sensational",  
            "astonishing",  
            "passionate",  
            "mysterious",  
            "delightful",  
            "aggressive",  
            "victorious",  
            "performers",  
            "penetrated",  
            "determined",  
            "attractive",  
            "accidental",  
            "unyielding",  
            "wonderful",  
            "imprinted",  
            "cherished",  
            "inscribed",  
            "demanding",  
            "treasured",  
            "reluctant",  
            "worshiped",  
            "sparkling",  
            "vivacious",  
            "beautiful",  
            "energetic",  
            "thrilling",  
            "animistic",  
            "desperate",  
            "admiring",  
            "stripped",  
            "romantic",  
            "intimate",  
            "precious",  
            "cavalier",  
            "scorched",  
            "delicate",  
            "mindless",  
            "careless",  
            "carefull",  
            "reverent",  
            "chemical",  
            "dominant",  
            "vigorous",  
            "fearless",  
            "alluring",  
            "handsome",  
            "opposite",  
            "puckered",  
            "generous",  
            "grateful",  
            "splendid",  
            "talented",  
            "fighting",  
            "physical",  
            "pleasant",  
            "ravaging",  
            "tempting",  
            "diligent",  
            "dazzling",  
            "victim’s",  
            "spirited",  
            "original",  
            "dripping",  
            "charming",  
            "heavenly",  
            "virginal",  
            "powerful",  
            "intense",  
            "vicious",  
            "damaged",  
            "favored",  
            "dearest",  
            "violent",  
            "gallant",  
            "darling",  
            "admired",  
            "desired",  
            "devoted",  
            "lustful",  
            "revered",  
            "captive",  
            "amazing",  
            "extreme",  
            "elegant",  
            "sexual",  
            "exposed",  
            "glowing",  
            "shining",  
            "special",  
            "selfish",  
            "jealous",  
            "aroused",  
            "excited",  
            "leather",  
            "muscled",  
            "perfect",  
            "bulging",  
            "ignited",  
            "pulsing",  
            "crushed",  
            "trusted",  
            "beloved",  
            "prized",  
            "heated",  
            "tender",  
            "loving",  
            "carnal",  
            "erotic",  
            "adored",  
            "lovely",  
            "sexual",  
            "bright",  
            "strong",  
            "ripped",  
            "french",  
            "honest",  
            "mutual",  
            "common",  
            "exotic",  
            "young",  
            "crazy",  
            "firey",  
            "close",  
            "fated",  
            "blind",  
            "brave",  
            "ideal",  
            "angry",  
            "naked",  
            "rough",  
            "eager",  
            "roped",  
            "alpha",  
            "cruel",  
            "bound",  
            "deep",  
            "true",  
            "wild",  
            "bare",  
            "pure",  
            "bold",  
            "dark",  
            "rare",  
            "tied",  
            "hard",  
            "sexy",  
            "hot"]
        listOfAdverbs = [            
            "tightly", 
            "joyously", 
            "more", 
            "shyly", 
            "unaccountably", 
            "frantically", 
            "dreamily", 
            "evenly", 
            "enormously", 
            "loudly", 
            "joyfully", 
            "quaintly", 
            "afterwards", 
            "eventually", 
            "nervously", 
            "truthfully", 
            "fortunately", 
            "daily", 
            "poorly", 
            "frightfully", 
            "equally", 
            "less", 
            "annually", 
            "officially", 
            "acidly", 
            "wildly", 
            "dimly", 
            "readily", 
            "weakly", 
            "fiercely", 
            "quietly", 
            "perfectly", 
            "judgmentally", 
            "regularly", 
            "gently", 
            "madly", 
            "knowledgeably", 
            "scarily", 
            "helpfully", 
            "enormously", 
            "never", 
            "mostly", 
            "gladly", 
            "greatly", 
            "frightfully", 
            "woefully", 
            "irritably", 
            "fortunately", 
            "ultimately", 
            "noisily", 
            "honestly", 
            "utterly", 
            "heavily", 
            "extremely", 
            "enthusiastically", 
            "reluctantly", 
            "patiently", 
            "kindly", 
            "faithfully", 
            "especially", 
            "courageously", 
            "rightfully", 
            "closely", 
            "gracefully", 
            "shakily", 
            "loosely", 
            "equally", 
            "commonly", 
            "oddly", 
            "coaxingly", 
            "exactly", 
            "helplessly", 
            "eventually", 
            "politely", 
            "likely", 
            "evenly", 
            "daringly", 
            "stealthily", 
            "foolishly", 
            "fervently", 
            "sometimes", 
            "repeatedly", 
            "greedily", 
            "valiantly", 
            "joyously", 
            "kindly", 
            "calmly", 
            "rightfully", 
            "daintily", 
            "interestingly", 
            "blindly", 
            "excitedly", 
            "joyfully", 
            "fairly", 
            "judgementally", 
            "merrily", 
            "excitedly", 
            "faithfully", 
            "madly", 
            "mysteriously", 
            "upside-down", 
            "briefly", 
            "busily", 
            "powerfully", 
            "lazily", 
            "diligently", 
            "ingeniously", 
            "keenly", 
            "nearly", 
            "beautifully", 
            "cheerfully", 
            "physically", 
            "promptly", 
            "victoriously", 
            "unnecessarily", 
            "ferociously", 
            "kiddingly", 
            "shyly", 
            "innocently", 
            "hopelessly", 
            "sympathetically", 
            "needily", 
            "fatally", 
            "freely", 
            "knowledgeably", 
            "unexpectedly", 
            "solemnly", 
            "zealously", 
            "owlishly", 
            "inadequately", 
            "lightly", 
            "speedily", 
            "noisily", 
            "inquisitively", 
            "openly", 
            "almost", 
            "doubtfully", 
            "lazily", 
            "sheepishly", 
            "tremendously", 
            "tomorrow", 
            "soon", 
            "nicely", 
            "helpfully", 
            "limply", 
            "obediently", 
            "miserably", 
            "faithfully", 
            "monthly", 
            "ferociously", 
            "sweetly", 
            "urgently", 
            "kookily", 
            "innocently", 
            "restfully", 
            "unimpressively", 
            "gently", 
            "tensely", 
            "terribly", 
            "rigidly", 
            "clearly", 
            "joyously", 
            "daintily", 
            "majestically", 
            "happily", 
            "generously", 
            "hungrily", 
            "dreamily", 
            "lively", 
            "only", 
            "energetically", 
            "rudely", 
            "always", 
            "anxiously", 
            "kindly", 
            "coolly", 
            "selfishly", 
            "seldom", 
            "questionably", 
            "optimistically", 
            "uselessly", 
            "wearily", 
            "immediately", 
            "gracefully", 
            "doubtfully", 
            "jovially", 
            "loftily", 
            "kissingly", 
            "dearly", 
            "inquisitively", 
            "vivaciously", 
            "potentially", 
            "cruelly", 
            "quickly", 
            "unethically", 
            "awkwardly", 
            "elegantly", 
            "fully", 
            "bleakly", 
            "foolishly", 
            "naturally", 
            "unbearably", 
            "playfully", 
            "knavishly", 
            "inquisitively", 
            "scarily", 
            "randomly", 
            "jaggedly", 
            "vastly", 
            "sedately", 
            "thoughtfully", 
            "helplessly", 
            "overconfidently", 
            "kindheartedly", 
            "suddenly", 
            "mysteriously", 
            "roughly", 
            "selfishly", 
            "mechanically", 
            "longingly", 
            "queasily", 
            "equally", 
            "zestfully", 
            "neatly", 
            "reproachfully", 
            "really", 
            "fortunately", 
            "speedily", 
            "instantly", 
            "triumphantly", 
            "elegantly", 
            "delightfully", 
            "hastily", 
            "openly", 
            "upright", 
            "stupidly", 
            "sleepily", 
            "kindheartedly", 
            "rudely", 
            "jubilantly", 
            "energetically", 
            "awkwardly", 
            "safely", 
            "keenly", 
            "poorly", 
            "beautifully", 
            "violently", 
            "rarely", 
            "solemnly", 
            "freely", 
            "sternly", 
            "justly", 
            "quicker", 
            "cheerfully", 
            "readily", 
            "poorly", 
            "slowly", 
            "sleepily", 
            "wrongly", 
            "vainly", 
            "vaguely", 
            "scarcely", 
            "rudely", 
            "exactly", 
            "interestingly", 
            "very", 
            "safely", 
            "easily", 
            "tightly", 
            "knowingly", 
            "wearily", 
            "gleefully", 
            "usefully", 
            "far", 
            "hourly", 
            "sadly", 
            "unfortunately", 
            "quickly", 
            "smoothly", 
            "silently", 
            "gracefully", 
            "fully", 
            "boldly", 
            "closely", 
            "continually", 
            "fast", 
            "rarely", 
            "knowingly", 
            "likely", 
            "honestly", 
            "broadly", 
            "swiftly", 
            "softly", 
            "slowly", 
            "sleepily", 
            "shrilly", 
            "famously", 
            "frenetically", 
            "certainly", 
            "extremely", 
            "offensively", 
            "vacantly", 
            "quizzically", 
            "accidentally", 
            "innocently", 
            "thankfully", 
            "mortally", 
            "defiantly", 
            "blissfully", 
            "recklessly", 
            "truthfully", 
            "less", 
            "swiftly", 
            "reassuringly", 
            "angrily", 
            "briskly", 
            "arrogantly", 
            "hourly", 
            "knottily", 
            "zestily", 
            "successfully", 
            "mysteriously", 
            "furiously", 
            "smoothly", 
            "intensely", 
            "hastily", 
            "sharply", 
            "shrilly", 
            "hungrily", 
            "roughly", 
            "abnormally", 
            "justly", 
            "punctually", 
            "nervously", 
            "weakly", 
            "busily", 
            "mortally", 
            "hurriedly", 
            "instantly", 
            "obnoxiously", 
            "often", 
            "shakily", 
            "even", 
            "enthusiastically", 
            "deceivingly", 
            "loyally", 
            "cautiously", 
            "dearly", 
            "rapidly", 
            "solemnly", 
            "anxiously", 
            "adventurously", 
            "enormously", 
            "quirkily", 
            "diligently", 
            "rapidly", 
            "victoriously", 
            "deliberately", 
            "wonderfully", 
            "sharply", 
            "brightly", 
            "cautiously", 
            "thoughtfully", 
            "usually", 
            "gladly", 
            "wholly", 
            "lively", 
            "quizzically", 
            "safely", 
            "jovially", 
            "quickly", 
            "carelessly", 
            "easily", 
            "youthfully", 
            "punctually", 
            "nicely", 
            "fondly", 
            "bashfully", 
            "unabashedly", 
            "suspiciously", 
            "quietly", 
            "furiously", 
            "vivaciously", 
            "only", 
            "politely", 
            "absentmindedly", 
            "warmly", 
            "smoothly", 
            "surprisingly", 
            "mostly", 
            "properly", 
            "happily", 
            "badly", 
            "rigidly", 
            "blindly", 
            "intently", 
            "inwardly", 
            "bravely", 
            "loftily", 
            "frankly", 
            "fondly", 
            "scarcely", 
            "delightfully", 
            "fast", 
            "loyally", 
            "absentmindedly", 
            "searchingly", 
            "cruelly", 
            "honestly", 
            "boastfully", 
            "sheepishly", 
            "shyly", 
            "fondly", 
            "curiously", 
            "gleefully", 
            "queerly", 
            "naturally", 
            "limply", 
            "quarrelsomely", 
            "loudly", 
            "joshingly", 
            "really", 
            "unexpectedly", 
            "nearly", 
            "healthily", 
            "regularly", 
            "slowly", 
            "delightfully", 
            "upliftingly", 
            "generally", 
            "deliberately", 
            "positively", 
            "actually", 
            "suspiciously", 
            "upbeat", 
            "tenderly", 
            "enthusiastically", 
            "suddenly", 
            "fiercely", 
            "generously", 
            "wetly", 
            "stealthily", 
            "patiently", 
            "dimly", 
            "fairly", 
            "seriously", 
            "eventually", 
            "greedily", 
            "quirkily", 
            "successfully", 
            "far", 
            "knavishly", 
            "highly", 
            "separately", 
            "justly", 
            "yesterday", 
            "silently", 
            "cleverly", 
            "correctly", 
            "voluntarily", 
            "jaggedlyjealously", 
            "partially", 
            "carelessly", 
            "powerfully", 
            "famously", 
            "roughly", 
            "repeatedly", 
            "defiantly", 
            "calmly", 
            "gladly", 
            "brightly", 
            "upbeat", 
            "mortally", 
            "rarely", 
            "immediately", 
            "eagerly", 
            "jealously", 
            "violently", 
            "courageously", 
            "solidly", 
            "noisily", 
            "healthily", 
            "unnaturally", 
            "kookily", 
            "gratefully", 
            "generally", 
            "sternly", 
            "rapidly", 
            "fiercely", 
            "greatly", 
            "truly", 
            "crossly", 
            "sharply", 
            "yawningly", 
            "fatally", 
            "exactly", 
            "sadly", 
            "thoroughly", 
            "bravely", 
            "irritably J", 
            "tenderly", 
            "generously", 
            "loosely", 
            "angrily", 
            "rightfully", 
            "fervently", 
            "lazily", 
            "frantically", 
            "obediently", 
            "meaningfully", 
            "wisely", 
            "speedily", 
            "deceivingly", 
            "carefully", 
            "quietly", 
            "intensely", 
            "happily", 
            "lightly", 
            "yearningly", 
            "righteously", 
            "really", 
            "doubtfully", 
            "frankly", 
            "elegantly", 
            "greedily", 
            "promptly", 
            "utterly", 
            "yearly", 
            "fatally", 
            "even", 
            "softly", 
            "seemingly", 
            "madly", 
            "inwardly", 
            "especially", 
            "boldly", 
            "well", 
            "badly", 
            "painfully", 
            "tensely", 
            "foolishly", 
            "frankly", 
            "gently", 
            "irritably", 
            "accidentally", 
            "intently", 
            "highly", 
            "reluctantly", 
            "lovingly", 
            "painfully", 
            "correctly", 
            "colorfully", 
            "deeply", 
            "frenetically", 
            "bitterly", 
            "upwardly", 
            "jubilantly", 
            "neatly", 
            "questioningly", 
            "truthfully", 
            "clearly", 
            "hungrily", 
            "strictly", 
            "hopelessly", 
            "verbally", 
            "carefully", 
            "kiddingly", 
            "warmly", 
            "heavily", 
            "upward", 
            "deeply", 
            "openly", 
            "viciously", 
            "sensibly", 
            "easily", 
            "worriedly", 
            "perfectly", 
            "softly", 
            "yieldingly", 
            "silently", 
            "willfully", 
            "seriously", 
            "frantically", 
            "healthily", 
            "deliberately", 
            "recklessly", 
            "hastily", 
            "mockingly", 
            "gratefully"]
        listOfNouns = [
            "factory reset button", 
            "blood rage", 
            "idiot", 
            "toaster", 
            "legend", 
            "death wish", 
            "therapy", 
            "goal in life", 
            "marketing idea", 
            "psychic", 
            "knife", 
            "sandwich", 
            "hunting ground", 
            "lettuce", 
            "kitty", 
            "friendly grandma", 
            "french chef", 
            "antidepressant drug", 
            "corn cake", 
            "president of the night", 
            "candlestick maker", 
            "coffee pot", 
            "brethren", 
            "national security agency", 
            "tank", 
            "useless brakes", 
            "international law enforcement agency", 
            "sound barrier", 
            "skinny woman", 
            "private investor", 
            "main people", 
            "stock car", 
            "elastic band", 
            "whole blood", 
            "telephone", 
            "mad cow disease", 
            "scourge upon the earth", 
            "rough-skinned newt", 
            "karate", 
            "pistol", 
            "legal warrant", 
            "people who are hurt", 
            "idea he suggested", 
            "party of the first part", 
            "place of business", 
            "double fault", 
            "kitty cat", 
            "famous landscape painting", 
            "hairy legs", 
            "old irish cottage", 
            "pocket flask", 
            "liquid oxygen", 
            "laser beams", 
            "preventive strike", 
            "dingle berry", 
            "reading party", 
            "generalized bond", 
            "indirect expression", 
            "messiness", 
            "love of her life", 
            "trust fund", 
            "volcanic crater", 
            "travel guidebook", 
            "electric furnace", 
            "internal respiration", 
            "police squad", 
            "mad-dog skullcap", 
            "sneaky criminal", 
            "new version", 
            "keepsake machete", 
            "gaming laptop", 
            "hissy fit", 
            "dog poop", 
            "dragon", 
            "mediation", 
            "patrolman", 
            "pervert", 
            "toilet seat", 
            "haunted graveyard", 
            "really tough guy", 
            "twinkling uncleanness", 
            "wrinkle", 
            "personal credit line", 
            "multi-billionaire", 
            "mental disorder", 
            "sweet tailpipe", 
            "boiling water", 
            "deer antler", 
            "background story", 
            "striped hyena", 
            "weed whacker", 
            "backstabbing misfortune", 
            "bad striped hyena", 
            "bat-shit crazy Amish folk", 
            "beautiful elastic band", 
            "best failure", 
            "big-bellied bad mood", 
            "bitchy peace offering", 
            "bloody indignation", 
            "bone-chilling legal warrant", 
            "boring heartbreak", 
            "bottle-conditioned trainer", 
            "bottled sweet tailpipe", 
            "brainless ways of the world", 
            "brewery-fresh sleazeball", 
            "bright-eyed double fault", 
            "brokenhearted druggie", 
            "bull-headed lover", 
            "busty descending color", 
            "buxom personality", 
            "cask-conditioned freak", 
            "cat-friendly reading party", 
            "caught-in-the-act jackass", 
            "chauvinistic pup", 
            "cheap natural history", 
            "cheeky keepsake machete", 
            "cheerful toilet seat", 
            "chilled good-for-nothing", 
            "chunky drug addict", 
            "cocky matrimonial law", 
            "cold-hearted Eskimo", 
            "colored snuggle bug", 
            "colossal love of her life", 
            "comforting grouch", 
            "comic divergent thinking", 
            "common toilet seat", 
            "compassionate bad mood", 
            "complex guilt", 
            "confrontational freak", 
            "considerate louse", 
            "contemporary queen", 
            "content dirtbag", 
            "control-top light bulb", 
            "corrupt broken promises", 
            "craft-brewed police squad", 
            "crappy lack of morality", 
            "crate-trained mood", 
            "crawly mistake", 
            "crazed master"]
        listOfNames = [
                        "Abel Crosby", 
            "Jaylan Church", 
            "Kolten Beard", 
            "Alfonso Cole", 
            "Liana Travis", 
            "Jaidyn Benton", 
            "Jazlene Grimes", 
            "Kane Obrien", 
            "Cory Tyler", 
            "Joyce Hopkins", 
            "Adelyn Richardson", 
            "Savannah Kent", 
            "Jase Frazier", 
            "Kaeden Mills", 
            "Liam Wu", 
            "Zaiden Knight", 
            "Efrain Olsen", 
            "Zackery Olsen", 
            "Luciano Dorsey", 
            "Waylon White", 
            "Raul Joseph", 
            "Magdalena Fitzgerald", 
            "Reese Mccann", 
            "Jaylee Spencer", 
            "Litzy Olsen", 
            "Emery Summers", 
            "Deangelo Jimenez", 
            "Trace Macias", 
            "Hana Padilla", 
            "Nash Best", 
            "Jakayla Shannon", 
            "Kamden Green", 
            "Crystal Cain", 
            "Niko Liu", 
            "Aniyah Foley", 
            "Colin Castro", 
            "Stephany Davies", 
            "Jacquelyn Oneill", 
            "Alma Riddle", 
            "Ryland White", 
            "Mariyah Conley", 
            "Karlee Lang", 
            "Jaeden Espinoza", 
            "Cruz Valenzuela", 
            "Priscilla Coleman", 
            "Amiah Nash", 
            "Matias Briggs", 
            "Paisley Porter", 
            "Dulce Hall", 
            "Parker Molina", 
            "Oscar Wolf", 
            "Richard Marshall", 
            "Kiley Friedman", 
            "Charity Spence", 
            "Jamir Steele", 
            "Nathanial Blanchard", 
            "Veronica Sutton", 
            "Misael Cooley", 
            "Claudia Wilkins", 
            "Madelyn Trujillo", 
            "Julius Parrish", 
            "Brandon Graham", 
            "Yaretzi Robbins", 
            "Emilee Holder", 
            "Elvis Thompson", 
            "Trevin Ferrell", 
            "Slade Norris", 
            "Carla Pruitt", 
            "Josh Love", 
            "Weston Steele", 
            "Phoebe Wilkerson", 
            "Memphis Dodson", 
            "Ibrahim White", 
            "Amiya Pierce", 
            "Kaiya Mcintosh", 
            "Tamara Reyes", 
            "Carley Lutz", 
            "Asia Andrade", 
            "Isabell Curry", 
            "Ayden Clements", 
            "Princess Hunter", 
            "Caroline Mitchell", 
            "Dakota Browning", 
            "Dangelo Hurley", 
            "Tyrone Chambers", 
            "Darien Walker"]
        randomTitle = ""
        randomTitle = randomTitle + random.choice(listOfAdverbs)
        randomTitle = randomTitle + " " + random.choice(listOfAdjectives)
        randomTitle = randomTitle + " " + random.choice(listOfNouns)
        randomName = ""
        randomName = randomName + random.choice(listOfNames)
        randomIsbn = random.randint(1000000000000, 9999999999999)
        randomIsbn = str(randomIsbn)
        randomBook = Book(randomIsbn, randomName, randomTitle)
        self.mainShelf.append(randomBook)
    
    def addTenRandomBooks(self):
        for x in range(0,10):
            x += 1
            self.addRandomBook()
    
    def initializeHistoryShelf(self):
        self.historyShelf.append(copy.deepcopy(self.mainShelf))
    
    def addBookToMainShelf(self, isbn, author, title):
        self.currentBook = Book(isbn, author, title)
        self.currentBook.addBookTo(self.mainShelf)
        self.historyShelf.append(copy.deepcopy(self.mainShelf))
    
    def printList(self):
        #print(self.mainShelf[0].isbn)
        for x in range(0, len(self.mainShelf)):
            print("")
            print("Book " + str(x + 1) + ": ")
            print("      isbn: " + self.mainShelf[x].isbn)
            print("      author: " + self.mainShelf[x].author)
            print("      title: " + self.mainShelf[x].title)
    
    def filterList(self, givenWord):
        for x in range(len(self.mainShelf) -1, -1, -1):
            titleName = self.mainShelf[x].title
            parts = titleName.split(" ")
            if parts[0] == givenWord:
                self.mainShelf.remove(self.mainShelf[x])
                del self.mainShelf[x:x]
        self.historyShelf.append(copy.deepcopy(self.mainShelf))
    
    def undoService(self):
        if len(self.historyShelf) == 1:
            print("")
            print("No more undo steps!")
        else:
            del self.historyShelf[-1]
            self.mainShelf = copy.deepcopy(self.historyShelf[-1])



